Traceback (most recent call last):
  File "C:\Users\carte\OneDrive\Desktop\Code\Paper-Trading\runner.py", line 21, in <module>
    from alpaca_trade_api import REST, APIError
ImportError: cannot import name 'APIError' from 'alpaca_trade_api' (C:\Python312\Lib\site-packages\alpaca_trade_api\__init__.py)
Traceback (most recent call last):
  File "C:\Users\carte\OneDrive\Desktop\Code\Paper-Trading\runner.py", line 21, in <module>
    from alpaca_trade_api import REST, APIError
ImportError: cannot import name 'APIError' from 'alpaca_trade_api' (C:\Python312\Lib\site-packages\alpaca_trade_api\__init__.py)
Traceback (most recent call last):
  File "C:\Users\carte\OneDrive\Desktop\Code\Paper-Trading\runner.py", line 21, in <module>
    from alpaca_trade_api import REST, APIError
ImportError: cannot import name 'APIError' from 'alpaca_trade_api' (C:\Python312\Lib\site-packages\alpaca_trade_api\__init__.py)
Traceback (most recent call last):
  File "C:\Users\carte\OneDrive\Desktop\Code\Paper-Trading\runner.py", line 21, in <module>
    from alpaca_trade_api import REST, APIError
ImportError: cannot import name 'APIError' from 'alpaca_trade_api' (C:\Python312\Lib\site-packages\alpaca_trade_api\__init__.py)
Traceback (most recent call last):
  File "C:\Users\carte\OneDrive\Desktop\Code\Paper-Trading\runner.py", line 21, in <module>
    from alpaca_trade_api import REST
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'APIError' from 'alpaca_trade_api' (C:\Python312\Lib\site-packages\alpaca_trade_api\__init__.py)
